name: Library build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Build Package
      run: npm run build

    - name: prepare package
      run: |
        mkdir out
        mv package.json out
        cp -r src/* out
        mv Readme.md out
        mv .gitignore out

    - name: List Contents of out folder
      run: ls -R out

    - name: Prepare Production Release
      uses: s0/git-publish-subdir-action@develop
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        REPO: self
        BRANCH: production
        FOLDER: out
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"

    - name: Publish to NPM
      run: |
        npm publish out
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}